Bug on jsonnet crd chart

diff --git a/bin/kubee-helm-post-renderer b/bin/kubee-helm-post-renderer
--- a/bin/kubee-helm-post-renderer
+++ b/bin/kubee-helm-post-renderer
@@ -213,17 +213,25 @@ jsonnet_processing(){
           # Closing
           POST_PROCESSING="$POST_PROCESSING'"
 
-          # Ext-code args is due Bug
-          # If a values has 3 ---,
-          # such as in -----BEGIN PRIVATE KEY-----,
-          # std.parseYaml will create an array
-          # https://github.com/google/go-jsonnet/issues/793
+          # The command
+          local JSONNET_COMMAND;
+          JSONNET_COMMAND=("jsonnet" "-J" "$JPATH" "--multi" "$JSONNET_OUTPUT_DIR" )
+
+          # Values files
+          # It may be empty for jsonnet crds
+          if [ "${KUBEE_VALUES_FILE:-}" != "" ]; then
+            # Ext-code args is due Bug
+            # If a values has 3 ---,
+            # such as in -----BEGIN PRIVATE KEY-----,
+            # std.parseYaml will create an array
+            # The ext-code check if it's an array, it takes the first element
+            # https://github.com/google/go-jsonnet/issues/793
+            JSONNET_COMMAND+=("--ext-code" "'values=(local valuesFile=std.parseYaml(importstr \"$KUBEE_VALUES_FILE\"); if std.isArray(valuesFile) && std.length(valuesFile) > 0 then valuesFile[0] else valuesFile)'")
+          fi
+
+          JSONNET_COMMAND+=("$JSONNET_FILE | $POST_PROCESSING")
           if ! JSONNET_MANIFEST=$(
-            echo::eval "jsonnet -J $JPATH \
-            --multi $JSONNET_OUTPUT_DIR \
-            --ext-code 'values=(local valuesFile=std.parseYaml(importstr \"$KUBEE_VALUES_FILE\"); if std.isArray(valuesFile) && std.length(valuesFile) > 0 then valuesFile[0] else valuesFile)' \
-            $JSONNET_FILE \
-            | $POST_PROCESSING"
+            echo::eval "${JSONNET_COMMAND[*]}"
           ); then
             echo::err "$JSONNET_MANIFEST"
             exit 1
@@ -252,15 +260,15 @@ synopsis(){
   cat <<EOF
 A post renderer to integrate \`kustomize\` and \`jsonnet\`
 \`\`\`bash
-$(basename "$0") appDirectory valuesPath namespace output_dir
+$(basename "$0") --chart-dir=chartDirectory --chart-values-path=valuesPath --chart-namespace=namespace --chart-output-dir=output_dir
 \`\`\`
 
 where:
 
-* \`KUBEE_CHART_DIRECTORY\` is the directory of the app to install
-* \`KUBEE_VALUES_FILE\` is the path to the values file
-* \`NAMESPACE\` is the installation namespace
-* \`OUTPUT_DIR\` is the output dir (Helm)
+* \`--chart-dir\`          : [Mandatory] the directory of the app to install
+* \`--chart-values-path\`  : [Optional]  the path to the values file (optional as its not mandatory for jsonnet crds chart)
+* \`--chart-namespace\`    : [Mandatory] the installation namespace
+* \`--chart-output-dir\`   : [Mandatory] the output dir (Helm)
 
 Note: Helm:
 * pass the templates output via stdin
@@ -268,43 +276,80 @@ Note: Helm:
 EOF
 }
 
-
-KUBEE_CHART_DIRECTORY="${1:-}"
-
-if [[ "$KUBEE_CHART_DIRECTORY" =~ "synopsis"|"help" ]]; then
+if [[ "$1" =~ "synopsis"|"help" ]]; then
   exec 1>&3 # Restore stdout because we want the synopsis output to stdout
   exec 3>&- # Close the saved descriptor
   synopsis > /dev/stdout
   exit 0
 fi
 
-if [ ! -d "$KUBEE_CHART_DIRECTORY" ]; then
-  echo::err "Internal Error: the first argument KUBEE_CHART_DIRECTORY ($KUBEE_CHART_DIRECTORY) is not a valid directory"
+# Parsing
+args=$(getopt -l "chart-output-dir:,chart-dir:,chart-namespace:,chart-values-path:,help" -o "h" -- "$@")
+# eval set to set the positional arguments back to $args
+eval set -- "$args"
+
+while [[ $# -gt 0 ]]; do
+   case $1 in
+    "--chart-output-dir")
+      shift
+      # Output
+      # The output dir is mandatory for Jsonnet or Kustomize processing
+      KUBEE_OUTPUT_DIR="$1"
+      ;;
+    "--chart-dir")
+      shift
+      KUBEE_CHART_DIRECTORY="${1}"
+      if [ ! -d "$KUBEE_CHART_DIRECTORY" ]; then
+        echo::err "Internal Error: the argument KUBEE_CHART_DIRECTORY ($KUBEE_CHART_DIRECTORY) is not a valid directory"
+        exit 1
+      fi
+    ;;
+    "--chart-values-path")
+      shift
+      # Values path is already generated at this point
+      # that's why we pass it and not regenerate it
+      KUBEE_VALUES_FILE="${1}"
+      # crds do not have any values file
+      if [ ! -f "$KUBEE_VALUES_FILE" ]; then
+        echo::err "Internal Error: the values path ($KUBEE_VALUES_FILE) is not a valid file"
+        exit 1
+      fi
+      ;;
+    "--chart-namespace")
+      shift
+      KUBEE_NAMESPACE="${1}"
+      ;;
+    "--help"|"-h")
+      synopsis
+      exit
+      ;;
+    "--")
+      break;
+      ;;
+    *)
+      echo "No optional argument is expected. The value ($1) is unexpected."
+      exit 1
+      ;;
+  esac
+  shift
+done
+
+if [ "${KUBEE_OUTPUT_DIR:-}" == "" ]; then
+    echo::err "Internal Error: KUBEE_OUTPUT_DIR should not be empty"
+    synopsis
+    exit 1
+fi
+
+if [ "${KUBEE_NAMESPACE:-}" == "" ]; then
+  echo::err "Internal Error: KUBEE_NAMESPACE should not be empty"
   exit 1
 fi
 
-# Values path is already generated at this point
-# that's why we pass it and not regenerate it
-KUBEE_VALUES_FILE="${2:-}"
-if [ ! -f "$KUBEE_VALUES_FILE" ]; then
-  echo::err "Internal Error: the second argument values path ($KUBEE_VALUES_FILE) is not a valid file"
+if [ "${KUBEE_CHART_DIRECTORY:-}" == "" ]; then
+  echo::err "Internal Error: KUBEE_CHART_DIRECTORY should not be empty"
   exit 1
 fi
 
-KUBEE_NAMESPACE="${3:-}"
-if [ "$KUBEE_NAMESPACE" == "" ]; then
-  echo::err "Internal Error: the third argument namespace should not be empty"
-  exit 1
-fi
-
-# Output
-# The output dir is mandatory for Jsonnet or Kustomize processing
-KUBEE_OUTPUT_DIR="${4}"
-if [ "$KUBEE_OUTPUT_DIR" == "" ]; then
-  echo::err "Internal Error: the fourth argument namespace should not be empty"
-  synopsis
-  exit 1
-fi
 
 # COMMAND_STDOUT_FD is exported from helm_x
 # where the output of stdout and stderr from external command should go
diff --git a/bin/kubee-helmet-helm b/bin/kubee-helmet-helm
--- a/bin/kubee-helmet-helm
+++ b/bin/kubee-helmet-helm
@@ -162,19 +162,24 @@ apply(){
     # App executions
     HELM_COMMAND+=("-f" "${CHART_VALUES_PATH}")
 
-    # Post renderer
-    HELM_COMMAND+=(
-      "--post-renderer" "kubee-helm-post-renderer"
-      "--post-renderer-args" "$CHART_DIRECTORY"
-      "--post-renderer-args" "$CHART_VALUES_PATH"
-      "--post-renderer-args" "$CHART_NAMESPACE"
-      "--post-renderer-args" "$CHART_OUTPUT_DIR"
-      )
-
     # Update dependencies if they are missing in the charts dir
     # It will create the Chart.lock
     # HELM_COMMAND+=("--dependency-update")
 
+  fi
+
+  # Post renderer
+
+  HELM_COMMAND+=(
+    "--post-renderer" "kubee-helm-post-renderer"
+    "--post-renderer-args" "--chart-dir=$CHART_DIRECTORY"
+    "--post-renderer-args" "--chart-namespace=$CHART_NAMESPACE"
+    "--post-renderer-args" "--chart-output-dir=$CHART_OUTPUT_DIR"
+    )
+  # We have jsonnet only CRD
+  # crd do not have any values file but we bash we can't pass empty
+  if [ "$CHART_TYPE" != "crds" ]; then
+      HELM_COMMAND+=("--post-renderer-args" "--chart-values-path=$CHART_VALUES_PATH")
   fi
 
 
@@ -224,13 +229,13 @@ apply(){
   # Redirect the error to capture it
   # We don't redirect to stdout because Helm put it also warning (ie without failing the command)
   # The output is then no more yaml compliant
-  # Example: walk.go:75: found symbolic link in path: /home/admin/code/kubee/resources/charts/mailu/charts/kubee-cluster resolves to /home/admin/code/kubee/resources/charts/cluster. Contents of linked file included and used
+  # Example: walk.go:75: found symbolic link in path: /home/admin/code/kubee/charts/mailu/charts/kubee-cluster resolves to /home/admin/code/kubee/resources/charts/cluster. Contents of linked file included and used
   local STDERR_FD="$KUBEE_RUNTIME_DIR"/helm_stderr.log
   rm -rf "$STDERR_FD"
   if ! HELM_OUTPUT=$(echo::eval "${HELM_COMMAND[*]}" "$STDERR_FD"); then
     echo::err "An error occurs during the command $COMMAND."
     echo::err "Output:"
-    echo::err "$(cat $STDERR_FD)"
+    echo::err "$(cat "$STDERR_FD")"
     return 1
   fi
 
@@ -267,7 +272,7 @@ apply(){
   # Can we Wait with that?
   # kubectl wait --for=condition=Ready pods -l  app.kubernetes.io/name=prometheus-operator
   #
-  if [ "$CHART_TYPE" == "crds" ]; then
+  if [ "$CHART_TYPE" == "crds" ] && [[ "$COMMAND" =~ "play"|"upgrade"|"install" ]]; then
     echo::info "Waiting until all CRD are established in the namespace $CHART_NAMESPACE"
     kubectl wait \
       --for condition=Established \
@@ -526,37 +531,46 @@ update-dependencies(){
             echo::eval "rm -rf $DEPENDENCY_DIR_PATH_IN_CHARTS"
           fi
 
-          # Get the url
-          # the url is the oci one
-          local DEPENDENCY_FULL_URL="$DEPENDENCY_CHART_REPOSITORY/$DEPENDENCY_CHART_NAME";
-          # for https, there is a little bit more work
-          if [ "$DEPENDENCY_CHART_SCHEME" == "https" ]; then
-            echo::info "$DEPENDENCY_CHART_NAME: Fetching $DEPENDENCY_CHART_SCHEME dependency $DEPENDENCY_CHART_NAME"
-            local REGISTRY_INDEX_YAML="$DEPENDENCY_CHART_REPOSITORY/index.yaml"
-            local DEPENDENCY_YAML_URL
-            if ! DEPENDENCY_YAML_URL=$(echo::eval "curl --location -s $REGISTRY_INDEX_YAML | yq '.entries[\"$DEPENDENCY_CHART_NAME\"][] | select(.version == \"$DEPENDENCY_CHART_VERSION\") | .urls[0]'"); then
-              echo::err "Error while retrieving the download url of the dependency char $DEPENDENCY_CHART_NAME"
-              return 1
-            fi
-            if [ "$DEPENDENCY_YAML_URL" == "" ] || [ "$DEPENDENCY_YAML_URL" == "null" ]; then
-              echo::err "No Url could be found to download $DEPENDENCY_CHART_NAME / $DEPENDENCY_CHART_VERSION in the index.yaml file ($REGISTRY_INDEX_YAML)"
-              return 1
-            fi
-            local DEPENDENCY_YAML_URL_SCHEME="${DEPENDENCY_YAML_URL%%:*}"
-            case "$DEPENDENCY_YAML_URL_SCHEME" in
-              "https"|"http"|"oci")
-                DEPENDENCY_FULL_URL="$DEPENDENCY_YAML_URL";
-                ;;
-              *)
-                # No scheme, relative url
-                DEPENDENCY_FULL_URL="$DEPENDENCY_CHART_REPOSITORY/$DEPENDENCY_YAML_URL";
-                ;;
-            esac
+          local HELM_PULL_COMMAND=("helm" "pull" "-d" "$CHART_CHARTS_DIRECTORY" "--untar")
 
-          fi
+          case "$DEPENDENCY_CHART_SCHEME" in
+            "https")
+              # for https, there is a little bit more work
+              echo::info "$DEPENDENCY_CHART_NAME: Fetching $DEPENDENCY_CHART_SCHEME dependency $DEPENDENCY_CHART_NAME"
+              local REGISTRY_INDEX_YAML="$DEPENDENCY_CHART_REPOSITORY/index.yaml"
+              local DEPENDENCY_YAML_URL
+              if ! DEPENDENCY_YAML_URL=$(echo::eval "curl --location -s $REGISTRY_INDEX_YAML | yq '.entries[\"$DEPENDENCY_CHART_NAME\"][] | select(.version == \"$DEPENDENCY_CHART_VERSION\") | .urls[0]'"); then
+                echo::err "Error while retrieving the download url of the dependency char $DEPENDENCY_CHART_NAME"
+                return 1
+              fi
+              if [ "$DEPENDENCY_YAML_URL" == "" ] || [ "$DEPENDENCY_YAML_URL" == "null" ]; then
+                echo::err "No Url could be found to download $DEPENDENCY_CHART_NAME / $DEPENDENCY_CHART_VERSION in the index.yaml file ($REGISTRY_INDEX_YAML)"
+                return 1
+              fi
+              local DEPENDENCY_YAML_URL_SCHEME="${DEPENDENCY_YAML_URL%%:*}"
+              case "$DEPENDENCY_YAML_URL_SCHEME" in
+                "https"|"http"|"oci")
+                  DEPENDENCY_FULL_URL="$DEPENDENCY_YAML_URL";
+                  ;;
+                *)
+                  # No scheme, relative url
+                  DEPENDENCY_FULL_URL="$DEPENDENCY_CHART_REPOSITORY/$DEPENDENCY_YAML_URL";
+                  ;;
+              esac
+              HELM_PULL_COMMAND+=("$DEPENDENCY_FULL_URL")
+              ;;
+            "oci")
+              DEPENDENCY_FULL_URL="$DEPENDENCY_CHART_REPOSITORY/$DEPENDENCY_CHART_NAME";
+              HELM_PULL_COMMAND+=("$DEPENDENCY_FULL_URL")
+              HELM_PULL_COMMAND+=("--version" "$DEPENDENCY_CHART_VERSION")
+              ;;
+            *)
+              echo::err "Dependency scheme unknown: $DEPENDENCY_CHART_SCHEME"
+              return 1
+          esac
 
           # Pull
-          if ! echo::eval "helm pull $DEPENDENCY_FULL_URL -d $CHART_CHARTS_DIRECTORY --untar"; then
+          if ! echo::eval "${HELM_PULL_COMMAND[*]}"; then
             echo::err "Error while pulling $DEPENDENCY_CHART_NAME"
             return 1
           fi
@@ -729,7 +743,11 @@ main(){
   # Values and namespace
   # Not for command
   # Not for CRD chart (namespace is given by the parent or manually)
-  if [[ ! "$COMMAND" =~ ^("update-dependencies"|"ping"|"crds")$ ]] && [ "$CHART_TYPE" != "crds" ]; then
+  local IS_VALUES_FILE_COMMAND=1
+  if [[ "$COMMAND" =~ ^("update-dependencies"|"ping"|"crds")$ ]]; then
+    IS_VALUES_FILE_COMMAND=0
+  fi
+  if [ "$IS_VALUES_FILE_COMMAND" == "1" ] && [ "$CHART_TYPE" != "crds" ]; then
       # The kubee values
       # We need them to determine the namespace
       CHART_VALUES_PATH="$CHART_OUTPUT_VALUES_DIR/values.yml"
@@ -755,13 +773,17 @@ main(){
       CHART_NAMESPACE="$KUBEE_CONNECTION_NAMESPACE"
     ;;
     *)
-      VALUES_NAMESPACE_PATH=".namespace"
-      CHART_NAMESPACE=$(yq "$VALUES_NAMESPACE_PATH" "$CHART_VALUES_PATH")
-      if [ "$CHART_NAMESPACE" == "null" ] || [ "$CHART_NAMESPACE" == "" ]; then
-        echo::err "No namespace found at path $VALUES_NAMESPACE_PATH on the file $CHART_VALUES_PATH"
-        exit 1
+      if [ "$IS_VALUES_FILE_COMMAND" == "1" ]; then
+        VALUES_NAMESPACE_PATH=".namespace"
+        CHART_NAMESPACE=$(yq "$VALUES_NAMESPACE_PATH" "$CHART_VALUES_PATH")
+        if [ "$CHART_NAMESPACE" == "null" ] || [ "$CHART_NAMESPACE" == "" ]; then
+          echo::err "No namespace found at path $VALUES_NAMESPACE_PATH on the file $CHART_VALUES_PATH"
+          exit 1
+        fi
+        echo::info "Namespace ($CHART_NAMESPACE) found in the values file at $VALUES_NAMESPACE_PATH"
+      else
+        CHART_NAMESPACE="$KUBEE_CONNECTION_NAMESPACE"
       fi
-      echo::info "Namespace ($CHART_NAMESPACE) found in the values file at $VALUES_NAMESPACE_PATH"
   esac
 
 
