Traefik on the move

diff --git a/bin/kube-x-cluster b/bin/kube-x-cluster
--- a/bin/kube-x-cluster
+++ b/bin/kube-x-cluster
@@ -4,30 +4,18 @@
 source "${BASHLIB_LIBRARY_PATH:-}${BASHLIB_LIBRARY_PATH:+/}bashlib-error.sh"
 error::set_strict_mode
 error::set_trap
-# shellcheck source=../..//bash-lib/lib/bashlib-echo.sh
+# shellcheck source=../../bash-lib/lib/bashlib-echo.sh
 source "${BASHLIB_LIBRARY_PATH:-}${BASHLIB_LIBRARY_PATH:+/}bashlib-echo.sh"
-# shellcheck source=../..//bash-lib/lib/bashlib-doc.sh
+# shellcheck source=../../bash-lib/lib/bashlib-doc.sh
 source "${BASHLIB_LIBRARY_PATH:-}${BASHLIB_LIBRARY_PATH:+/}bashlib-doc.sh"
-# shellcheck source=../..//bash-lib/lib/bashlib-command.sh
+# shellcheck source=../../bash-lib/lib/bashlib-command.sh
 source "${BASHLIB_LIBRARY_PATH:-}${BASHLIB_LIBRARY_PATH:+/}bashlib-command.sh"
+# shellcheck source=../../bash-lib/lib/bashlib-template.sh
+source "${BASHLIB_LIBRARY_PATH:-}${BASHLIB_LIBRARY_PATH:+/}bashlib-template.sh"
 
 SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 
-# Check that a file has all variable
-check_vars() {
 
-  local ENVS=$(envsubst -v "$(cat $1)")
-  local rc=0
-  while read VARIABLE_NAME
-  do
-      if [ "${!VARIABLE_NAME:-}" == "" ]; then
-          echo::err "$VARIABLE_NAME is not defined and should be defined"
-          rc=1
-      fi
-  done <<< $ENVS
-  return "$rc"
-
-}
 
 play(){
 
@@ -39,16 +27,16 @@ play(){
 inventory_file(){
 
    # Inventory
-   KUBE_X_INVENTORY_FILE="${KUBE_X_INVENTORY_FILE:-"${SCRIPT_DIR}/../resources/cluster/provisioning/inventory.yml"}"
+   local KUBE_X_INVENTORY_FILE="${KUBE_X_INVENTORY_FILE:-"${SCRIPT_DIR}/../resources/cluster/kube-x/ansible-inventory.yml"}"
 
    # Check the variables
-   if ! check_vars "$KUBE_X_INVENTORY_FILE"; then
+   if ! UNDEFINED_VARS=$(template::check_vars -f "$KUBE_X_INVENTORY_FILE"); then
      # Should exit because of the strict mode
      # but it was not working
-     echo::err "Inventory variables missing"
+     echo::err "Inventory variables missing: ${UNDEFINED_VARS[*]}"
      return 1
    fi
-   local SHM_INVENTORY_FILE="/dev/shm/kube-x-inventory.yml"
+   local SHM_INVENTORY_FILE="/dev/shm/kube-x-ansible-inventory.yml"
 
    envsubst < "$KUBE_X_INVENTORY_FILE" >| "$SHM_INVENTORY_FILE"
    echo "$SHM_INVENTORY_FILE"
diff --git a/bin/kube-x-cluster-app b/bin/kube-x-cluster-app
--- a/bin/kube-x-cluster-app
+++ b/bin/kube-x-cluster-app
@@ -8,8 +8,35 @@ error::set_trap
 source "${BASHLIB_LIBRARY_PATH:-}${BASHLIB_LIBRARY_PATH:+/}bashlib-echo.sh"
 # shellcheck source=../../bash-lib/lib/bashlib-doc.sh
 source "${BASHLIB_LIBRARY_PATH:-}${BASHLIB_LIBRARY_PATH:+/}bashlib-doc.sh"
+# shellcheck source=../../bash-lib/lib/bashlib-template.sh
+source "${BASHLIB_LIBRARY_PATH:-}${BASHLIB_LIBRARY_PATH:+/}bashlib-template.sh"
 # shellcheck source=./kube-x-lib.sh
 source "kube-x-lib.sh"
+
+
+generate_and_get_helm_values_path(){
+
+  # Default
+  # export is mandatory to go in a subshell
+  export KUBE_X_CLUSTER_PROMETHEUS_ENABLED="${KUBE_X_CLUSTER_PROMETHEUS_ENABLED:-false}"
+
+  # Template
+  SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
+  local KUBE_X_HELM_VALUES="${SCRIPT_DIR}/../resources/cluster/kube-x/helm-values.yml"
+
+  # Check the variables
+  if ! UNDEFINED_VARS=$(template::check_vars -f "$KUBE_X_HELM_VALUES"); then
+     # Should exit because of the strict mode
+     # but it was not working
+     echo::err "Helm Values variables missing: ${UNDEFINED_VARS[*]}"
+     return 1
+  fi
+  local SHM_HELM_VALUES="/dev/shm/kube-x-helm-values.yml"
+
+  envsubst < "$KUBE_X_HELM_VALUES" >| "$SHM_HELM_VALUES"
+  echo "$SHM_HELM_VALUES"
+
+}
 
 install(){
   APP_NAME="${1:-}"
@@ -39,8 +66,13 @@ install(){
   echo $APP_DIRECTORY
   pushd "$APP_DIRECTORY"
   APP_RELEASE_NAME="$APP_NAMESPACE"
-  local SETS=()
-  SETS+=("--set kube_x.prometheus.enabled=${KUBE_X_CLUSTER_PROMETHEUS_ENABLED:-false}")
+
+  # The kube-x values
+  if ! KUBE_X_VALUES_PATH=$(generate_and_get_helm_values_path); then
+    echo::err "Error while trying to get the kube-x-helm values"
+    return 1
+  fi
+
   # --dependency-update flag to avoid the `helm dependency build` error:
   # `Error: no repository definition for https://traefik.github.io/charts. Please add the missing repos via 'helm repo add'`
   # See https://github.com/helm/helm/issues/7214
@@ -50,7 +82,7 @@ install(){
     --create-namespace \
     --dependency-update \
     -f values.yml \
-    ${SETS[*]} \
+    -f $KUBE_X_VALUES_PATH \
     $APP_RELEASE_NAME \
     ."
   popd
@@ -96,6 +128,9 @@ case "$COMMAND" in
     ;;
   "synopsis")
     synopsis
+    ;;
+  "values")
+    cat "$(generate_and_get_helm_values_path)"
     ;;
   *)
     doc::help synopsis
