Kustomize done. Error on stdout

diff --git a/bin/kube-x-helm-post-renderer b/bin/kube-x-helm-post-renderer
--- a/bin/kube-x-helm-post-renderer
+++ b/bin/kube-x-helm-post-renderer
@@ -1,4 +1,15 @@
 #!/bin/bash
+
+# To avoid weird error on output
+# Helm takes /dev/stdout and validate it
+# ie unbelievable error such as:
+# Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: invalid object to validate
+# We redirect stdout to stderr and restore it just before the end
+# First save the original stdout
+exec 3>&1
+# Redirect all stdout to stderr
+exec 1>&2
+
 # A post renderer to integrate kustomize and jsonnet
 # shellcheck source=../..//bash-lib/lib/bashlib-error.sh
 source "${BASHLIB_LIBRARY_PATH:-}${BASHLIB_LIBRARY_PATH:+/}bashlib-error.sh"
@@ -15,6 +26,50 @@ source "${BASHLIB_LIBRARY_PATH:-}${BASHLIB_LIBRARY_PATH:+/}bashlib-command.sh"
 # shellcheck source=kube-x-lib.sh
 source kube-x-lib.sh
 
+
+# Check that a target directory has the same files than a source directory (in name not size)
+# Create an empty file in the target directory if a source file was not found
+#
+# Why?
+# Kustomize expects to have a file for all resources and patches
+# but template Files may return an empty string and the files are not created
+# if we use comments to not get an empty file
+# The validation fails with
+# Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: invalid object to validate
+# Disabling with --skip-schema-validation would not work
+# Without any solution, we have written this function
+create_empty_templates_with_empty_files(){
+
+  # Source and target templates directories
+  SOURCE_DIR="${1:-}"
+  TARGET_DIR="${2:-}"
+
+  # Check if both directories are provided
+  if [[ "$SOURCE_DIR" == "" || "$TARGET_DIR" == "" ]]; then
+    echo::err "Usage: $0 <source_directory> <target_directory>"
+    return 1
+  fi
+
+  # Traverse the source directory
+  find "$SOURCE_DIR" -type f -name "*.yaml" -o -name "*.yml" | while read -r source_file; do
+    # Get the relative path of the file
+    relative_path="${source_file#"$SOURCE_DIR"/}"
+    target_file="$TARGET_DIR/$relative_path"
+
+    # Check if the file exists in the target directory
+    if [[ ! -f "$target_file" ]]; then
+      # Create an empty file in the target directory
+      mkdir -p "$(dirname "$target_file")"
+      touch "$target_file"
+      echo::info "Template File $target_file Status: Created"
+    else
+      echo::debug "Template File $target_file Status: Exists"
+    fi
+  done
+
+}
+
+
 KUBE_X_CHART_DIRECTORY="${1:-}"
 
 if [[ "$KUBE_X_CHART_DIRECTORY" =~ "synopsis"|"help" ]]; then
@@ -30,7 +85,9 @@ where:
 * \`KUBE_X_VALUES_FILE\` is the path to the values file
 * \`KUBE_X_NAMESPACE\` is the installation namespace
 
-Note: the Helm templates should be passed via stdin
+Note: Helm:
+* pass the templates output via stdin
+* will not print any output if no error occurs (even with the --debug flag)
 EOF
   exit 0
 fi
@@ -72,6 +129,7 @@ fi
 
 # Grab the manifests passed by Helm
 HELM_MANIFEST=$(cat)
+
 # In kustomization mode, the templates are re-created individually
 # because we don't known which one is a resource and which one is a patch
 # The kustomization file is the driver
@@ -160,6 +218,10 @@ if [ "$KUSTOMIZATION_MODE" -eq 1 ]; then
   # will output all templates one by one at: $KUSTOMIZE_ROOT_TEMP_DIR/chart-name/templates/argocd-service-monitor-metrics.yml
   command::echo_eval "helm template --output-dir $KUSTOMIZE_ROOT_TEMP_DIR -f $KUBE_X_VALUES_FILE $KUBE_X_CHART_DIRECTORY"
 
+  # Sync
+  echo::info "Create empty template files"
+  create_empty_templates_with_empty_files "$KUBE_X_CHART_DIRECTORY/templates" "$KUSTOMIZE_PACKAGE_TEMP_DIR/templates"
+
   # The argument must be:
   # * a file system path
   # * or git repository path (git URL with path)
@@ -174,15 +236,16 @@ if [ "$KUSTOMIZATION_MODE" -eq 1 ]; then
     if [ "$BASHLIB_ECHO_LEVEL" != "$BASHLIB_ECHO_DEBUG_LEVEL" ]; then
       rm -rf "$KUSTOMIZE_PACKAGE_TEMP_DIR"
     else
-      echo::err "The command 'kubectl kustomize .' was executed with the $KUSTOMIZE_PACKAGE_TEMP_DIR working directory"
+      echo::info "The command 'kubectl kustomize .' was executed with the $KUSTOMIZE_PACKAGE_TEMP_DIR working directory"
     fi
     # Add the kustomize manifest to the Jsonnet manifest if any
-    HELM_MANIFEST=$(cat <<EOF
-$HELM_MANIFEST
----
-$KUSTOMIZE_MANIFEST
-EOF
-)
+    HELM_MANIFEST="$KUSTOMIZE_MANIFEST"
+#    HELM_MANIFEST=$(cat <<EOF
+#$HELM_MANIFEST
+#---
+#$KUSTOMIZE_MANIFEST
+#EOF
+#)
   else
     echo::err "An error occurred during the kustomization"
     echo::err "The command 'kubectl kustomize .' failed with the $KUSTOMIZE_PACKAGE_TEMP_DIR working directory"
@@ -191,4 +254,10 @@ EOF
 fi
 
 # Output
+
+# Later, restore stdout from saved descriptor
+exec 1>&3
+# Close the saved descriptor
+exec 3>&-
+
 echo "$HELM_MANIFEST"
diff --git a/bin/kube-x-helm-x b/bin/kube-x-helm-x
--- a/bin/kube-x-helm-x
+++ b/bin/kube-x-helm-x
@@ -88,6 +88,179 @@ is_helm_chart_installed() {
 
 }
 
+
+
+apply(){
+
+  # The final helm command (installation, or template)
+  local HELM_COMMAND=("helm")
+
+  # Package Name
+  # Come first because we use it in the log
+  PACKAGE_NAME="${2:-}"
+  if [ "$PACKAGE_NAME" == "" ]; then
+    echo::err "A package name is mandatory as second argument"
+    return 1
+  fi
+
+  # Mode
+  COMMAND=${1:-}
+  if [ "$COMMAND" == "" ]; then
+    echo::err "Internal error: A command is mandatory as first argument (install or template)"
+    return 1
+  fi
+  case "$COMMAND" in
+      "install")
+        HELM_COMMAND+=( "upgrade" "--install" )
+        echo::info "Installing package $PACKAGE_NAME "
+        ;;
+      "template")
+        HELM_COMMAND+=( "template" )
+        echo::info "Templating package $PACKAGE_NAME "
+        ;;
+      *)
+        echo::err "The command $COMMAND is unknown"
+        return 1
+        ;;
+  esac
+
+
+  # Get env (KubeConfig) used by helm for CRD Chart and app Chart
+  KUBECTX_ENV=$(source kubectl-xenv) || error::exit $?
+  eval "$KUBECTX_ENV"
+
+  # The kube-x values
+  # We need them to determine the namespace
+  KUBE_X_VALUES_PATH="/dev/shm/kube-x-values.yml"
+  if ! print_values >| $KUBE_X_VALUES_PATH; then
+    echo::err "An error has happened while generating the values file"
+    return 1
+  fi
+  # In debug mode, we don't delete it to be able to run the
+  # command again
+  if [ "$BASHLIB_ECHO_LEVEL" != "$BASHLIB_ECHO_DEBUG_LEVEL" ]; then
+    bash::trap "rm $KUBE_X_VALUES_PATH" EXIT # EXIT execute also on error
+  fi
+  HELM_COMMAND+=("-f" "${KUBE_X_VALUES_PATH}")
+
+  # Package
+  PACKAGE_DIRECTORY=$(get_chart_directory "$PACKAGE_NAME")
+  PACKAGE_YAML_KEY=$(echo "$PACKAGE_NAME" | tr "-" "_") # Go templating does not support `-`
+  VALUES_NAMESPACE_PATH=".kube_x.$PACKAGE_YAML_KEY.namespace"
+  PACKAGE_NAMESPACE=$(yq "$VALUES_NAMESPACE_PATH" "$KUBE_X_VALUES_PATH")
+  if [ "$PACKAGE_NAMESPACE" == "null" ]; then
+    echo::info "No namespace found at $VALUES_NAMESPACE_PATH"
+    PACKAGE_NAMESPACE="$PACKAGE_NAME"
+    echo::info "Installing into the default namespace $PACKAGE_NAMESPACE"
+  else
+    echo::info "Installing into the namespace ($PACKAGE_NAMESPACE) found in the values file at $VALUES_NAMESPACE_PATH"
+  fi
+  HELM_COMMAND+=(
+    "-n" "$PACKAGE_NAMESPACE"
+    "--create-namespace"
+  )
+
+
+  # Crds first
+  # CRD first installation is becoming a standard
+  # Example with Prometheus: https://github.com/prometheus-operator/kube-prometheus#quickstart
+  # They create the namespace and CustomResourceDefinitions first
+  # to avoid race conditions when deploying the components.
+  #
+  # We could also do
+  #```bash
+  # kubectl apply --server-side --force-conflicts -f https://github.com/grafana/grafana-operator/releases/download/v5.15.1/crds.yaml
+  #```
+  PACKAGE_CRDS_NAME="$PACKAGE_NAME-crds"
+  if PACKAGE_CRDS_DIRECTORY=$(get_chart_directory "$PACKAGE_CRDS_NAME"); then
+    echo::debug "Package Crds Directory: $PACKAGE_CRDS_DIRECTORY"
+
+    CHART_APP_VERSION=$(yq '.appVersion' "$PACKAGE_DIRECTORY/Chart.yaml")
+    if ! is_helm_chart_installed "$PACKAGE_CRDS_NAME" "$PACKAGE_NAMESPACE" "$CHART_APP_VERSION"; then
+
+      command::echo_eval "helm upgrade --install -n $PACKAGE_NAMESPACE ${HELM_EXTRA_FLAGS[*]} --create-namespace $PACKAGE_CRDS_NAME $PACKAGE_CRDS_DIRECTORY"
+
+      # Wait
+      echo::info "Waiting until all CRD are established in the namespace $PACKAGE_NAMESPACE"
+      kubectl wait \
+      	--for condition=Established \
+      	--all CustomResourceDefinition \
+      	--namespace="$PACKAGE_NAMESPACE"
+
+    else
+      echo::info "CRD Chart $PACKAGE_CRDS_NAME already installed"
+    fi
+  else
+    echo::info "No CRD Chart for package $PACKAGE_NAME found"
+  fi
+
+
+  # To update the kube-x helm
+  command::echo_eval "helm dependency update ${HELM_EXTRA_FLAGS[*]} $PACKAGE_DIRECTORY 1>&2"
+  HELM_COMMAND+=( "--dependency-update" )
+
+  # Options ???
+  if [ "${KUBE_X_HELM_INSTALL_OPTIONS:-}" != "" ]; then
+    HELM_COMMAND+=("${KUBE_X_HELM_INSTALL_OPTIONS[@]}")
+  fi
+
+  # Post renderer
+  HELM_COMMAND+=(
+    "--post-renderer" "kube-x-helm-post-renderer"
+    "--post-renderer-args" "$PACKAGE_DIRECTORY"
+    "--post-renderer-args" "$KUBE_X_VALUES_PATH"
+    "--post-renderer-args" "$PACKAGE_NAMESPACE"
+    )
+
+  # Debug
+  if [ "${#HELM_EXTRA_FLAGS[*]}" != "0" ]; then
+    HELM_COMMAND+=("${HELM_EXTRA_FLAGS[@]}")
+  fi
+
+  # --dependency-update flag to avoid the `helm dependency build` error:
+  # `Error: no repository definition for https://traefik.github.io/charts. Please add the missing repos via 'helm repo add'`
+  # See https://github.com/helm/helm/issues/7214
+  # values.yaml file is taken by default
+  PACKAGE_RELEASE_NAME="$PACKAGE_NAME"
+  HELM_COMMAND+=("$PACKAGE_RELEASE_NAME" "$PACKAGE_DIRECTORY")
+
+
+  # Working directory is the cluster directory
+  # Why? To be able to set relative path to the cluster object such as certificate
+  # example: "--set-file kube_x.traefik.defaultCertificate.cert=cert/kube-x.dev+1.pem"
+  pushd "$KUBE_X_CLUSTER_DIR" 1>&2
+  command::echo_eval "${HELM_COMMAND[*]}"
+  popd 1>&2
+
+  # Wait?
+  # kubectl wait --for=condition=Ready pods -l  app.kubernetes.io/name=prometheus-operator
+
+}
+
+
+# The synopsis function is required by the doc::usage
+synopsis(){
+
+  cat << EOF
+\`\`\`bash
+kube-x-helx [-c|--cluster clusterName] [--debug] command options
+\`\`\`
+
+where \`command\` can be:
+
+* \`install packageName\`  - Install a Helx package (with optional Jsonnet Manifests and kustomization)
+* \`template packageName\` - Output the manifests for an package (used for ArgoCd Integration and debugging)
+* \`values\` - Shows the values
+
+The cluster is determined in order of precedence by:
+
+* the \`-c|--cluster clusterName\` option
+* the current directory
+
+EOF
+
+}
+
 # @description
 #     Print the kube-x values files used for Helm Installation and Jsonnet Configuration
 # @stdout - the values
@@ -139,180 +312,30 @@ print_values(){
 
 }
 
-apply(){
-
-  # The final helm command (installation, or template)
-  local HELM_COMMAND=("helm")
-
-  # Package Name
-  # Come first because we use it in the log
-  PACKAGE_NAME="${2:-}"
-  if [ "$PACKAGE_NAME" == "" ]; then
-    echo::err "A package name is mandatory as second argument"
-    return 1
-  fi
-
-  # Mode
-  COMMAND=${1:-}
-  if [ "$COMMAND" == "" ]; then
-    echo::err "Internal error: A command is mandatory as first argument (install or template)"
-    return 1
-  fi
-  case "$COMMAND" in
-      "install")
-        HELM_COMMAND+=( "upgrade" "--install" )
-        echo::info "Installing package $PACKAGE_NAME "
-        ;;
-      "template")
-        HELM_COMMAND+=( "template" )
-        echo::info "Templating package $PACKAGE_NAME "
-        ;;
-      *)
-        echo::err "The command $COMMAND is unknown"
-        return 1
-        ;;
-  esac
-
-
-  # Get env (KubeConfig) used by helm for CRD Chart and app Chart
-  KUBECTX_ENV=$(source kubectl-xenv) || error::exit $?
-  eval "$KUBECTX_ENV"
-
-  # The kube-x values
-  # We need them to determine the namespace
-  KUBE_X_VALUES_PATH="/dev/shm/kube-x-values.yml"
-  if ! print_values >| $KUBE_X_VALUES_PATH; then
-    echo::err "An error has happened while generating the values file"
-    return 1
-  fi
-  bash::trap "rm $KUBE_X_VALUES_PATH" EXIT # EXIT execute also on error
-  HELM_COMMAND+=("-f" "${KUBE_X_VALUES_PATH}")
-
-  # Package
-  PACKAGE_DIRECTORY=$(get_chart_directory "$PACKAGE_NAME")
-  PACKAGE_YAML_KEY=$(echo "$PACKAGE_NAME" | tr "-" "_") # Go templating does not support `-`
-  VALUES_NAMESPACE_PATH=".kube_x.$PACKAGE_YAML_KEY.namespace"
-  PACKAGE_NAMESPACE=$(yq "$VALUES_NAMESPACE_PATH" "$KUBE_X_VALUES_PATH")
-  if [ "$PACKAGE_NAMESPACE" == "null" ]; then
-    echo::info "No namespace found at $VALUES_NAMESPACE_PATH"
-    PACKAGE_NAMESPACE="$PACKAGE_NAME"
-    echo::info "Installing into the default namespace $PACKAGE_NAMESPACE"
-  else
-    echo::info "Installing into the namespace ($PACKAGE_NAMESPACE) found in the values file at $VALUES_NAMESPACE_PATH"
-  fi
-  HELM_COMMAND+=(
-    "-n" "$PACKAGE_NAMESPACE"
-    "--create-namespace"
-  )
-
-
-  # Crds first
-  # CRD first installation is becoming a standard
-  # Example with Prometheus: https://github.com/prometheus-operator/kube-prometheus#quickstart
-  # They create the namespace and CustomResourceDefinitions first
-  # to avoid race conditions when deploying the components.
-  #
-  # We could also do
-  #```bash
-  # kubectl apply --server-side --force-conflicts -f https://github.com/grafana/grafana-operator/releases/download/v5.15.1/crds.yaml
-  #```
-  PACKAGE_CRDS_NAME="$PACKAGE_NAME-crds"
-  if PACKAGE_CRDS_DIRECTORY=$(get_chart_directory "$PACKAGE_CRDS_NAME"); then
-    echo::debug "Package Crds Directory: $PACKAGE_CRDS_DIRECTORY"
-
-    CHART_APP_VERSION=$(yq '.appVersion' "$PACKAGE_DIRECTORY/Chart.yaml")
-    if ! is_helm_chart_installed "$PACKAGE_CRDS_NAME" "$PACKAGE_NAMESPACE" "$CHART_APP_VERSION"; then
-
-      command::echo_eval "helm upgrade --install -n $PACKAGE_NAMESPACE --create-namespace $PACKAGE_CRDS_NAME $PACKAGE_CRDS_DIRECTORY"
-
-      # Wait
-      echo::info "Waiting until all CRD are established in the namespace $PACKAGE_NAMESPACE"
-      kubectl wait \
-      	--for condition=Established \
-      	--all CustomResourceDefinition \
-      	--namespace="$PACKAGE_NAMESPACE"
-
-    else
-      echo::info "CRD Chart $PACKAGE_CRDS_NAME already installed"
-    fi
-  else
-    echo::info "No CRD Chart for package $PACKAGE_NAME found"
-  fi
-
-
-  # To update the kube-x helm
-  command::echo_eval "helm dependency update $PACKAGE_DIRECTORY 1>&2"
-  HELM_COMMAND+=( "--dependency-update" )
-
-  # Options ???
-  if [ "${KUBE_X_HELM_INSTALL_OPTIONS:-}" != "" ]; then
-    HELM_COMMAND+=("${KUBE_X_HELM_INSTALL_OPTIONS[@]}")
-  fi
-
-  # Post renderer
-  HELM_COMMAND+=(
-    "--post-renderer" "kube-x-helm-post-renderer"
-    "--post-renderer-args" "$PACKAGE_DIRECTORY"
-    "--post-renderer-args" "$KUBE_X_VALUES_PATH"
-    "--post-renderer-args" "$PACKAGE_NAMESPACE"
-    )
-
-  # --dependency-update flag to avoid the `helm dependency build` error:
-  # `Error: no repository definition for https://traefik.github.io/charts. Please add the missing repos via 'helm repo add'`
-  # See https://github.com/helm/helm/issues/7214
-  # values.yaml file is taken by default
-  PACKAGE_RELEASE_NAME="$PACKAGE_NAME"
-  HELM_COMMAND+=("$PACKAGE_RELEASE_NAME" "$PACKAGE_DIRECTORY")
-
-  # Working directory is the cluster directory
-  # Why? To be able to set relative path to the cluster object such as certificate
-  # example: "--set-file kube_x.traefik.defaultCertificate.cert=cert/kube-x.dev+1.pem"
-  pushd "$KUBE_X_CLUSTER_DIR" 1>&2
-  command::echo_eval "${HELM_COMMAND[*]}"
-  popd 1>&2
-
-  # Wait?
-  # kubectl wait --for=condition=Ready pods -l  app.kubernetes.io/name=prometheus-operator
-
-}
-
-
-# The synopsis function is required by the doc::usage
-synopsis(){
-
-  cat << EOF
-\`\`\`bash
-kube-x-helx [-c|--cluster clusterName] command options
-\`\`\`
-
-where \`command\` can be:
-
-* \`install packageName\`  - Install a Helx package (with optional Jsonnet Manifests and kustomization)
-* \`template packageName\` - Output the manifests for an package (used for ArgoCd Integration and debugging)
-* \`values\` - Shows the values
-
-The cluster is determined in order of precedence by:
-
-* the \`-c|--cluster clusterName\` option
-* the current directory
-
-EOF
-
-}
 
 ##########################
 ## Collect the options
 ##########################
-args=$(getopt -l "cluster:" -o "c:" -- "$@")
+args=$(getopt -l "cluster:,debug,skip-schema-validation" -o "c:" -- "$@")
 # eval set to set the positional arguments back to $args
 eval set -- "$args"
 KUBE_X_CLUSTER_NAME=${KUBE_X_CLUSTER_NAME:-}
+HELM_EXTRA_FLAGS=()
 while [[ $# -gt 0 ]]
 do
    case "$1" in
       "--cluster"|"-c")
         shift
         KUBE_X_CLUSTER_NAME=${1}
+        shift
+      ;;
+      "--skip-schema-validation")
+        shift
+        HELM_EXTRA_FLAGS+=("--skip-schema-validation")
+        ;;
+      "--debug")
+        export BASHLIB_ECHO_LEVEL="$BASHLIB_ECHO_DEBUG_LEVEL"
+        HELM_EXTRA_FLAGS+=("--debug")
         shift
       ;;
       "--")
