Added secret cert

diff --git a/bin/kube-cert b/bin/kube-cert
--- a/bin/kube-cert
+++ b/bin/kube-cert
@@ -8,31 +8,67 @@
 set -Eeuo pipefail
 source bashlib-echo.sh
 source bashlib-error.sh
-source bashlib-path.sh
-source bashlib-command.sh
-source bashlib-crypto.sh
 error::set_trap
 
-HELP=${1:-}
-if [[ $HELP =~ -h|--help|help ]]; then
+usage(){
+
   echo "Usage:"
   echo ''
-  echo 'Return the kubeconfig certs in plain text'
+  echo 'Return the certs in plain text'
   echo ''
   echo '```bash'
   # shellcheck disable=SC2005
-  echo "$(basename "$0")"
+  echo "$(basename "$0") command"
   echo '```'
+  echo "where: command may be:"
+  # shellcheck disable=SC2016
+  echo '  * `config` : Print the client certificate in the kubeconfig file'
+  # shellcheck disable=SC2016
+  echo '  * `secret` : Print the client certificate in a secret'
+
+}
+HELP=${1:-}
+if [[ $HELP =~ -h|--help|help ]]; then
+  usage
   exit
 fi
 
+function print_cert_secret(){
+  # <() is a https://en.wikipedia.org/wiki/Process_substitution to give a file (ie URI)
+  SECRET_NAME=$1
+  SECRET_NAMESPACE=$2
+  openssl storeutl -noout -text <(kubectl get secret -n "$SECRET_NAMESPACE" "$SECRET_NAME" -o jsonpath='{.data.tls\.crt}' | base64 -d)
+}
+
+function print_cert_kubeconfig(){
+  # openssl storeutl permits to read a bundle. Take a file as input
+  openssl storeutl -noout -text <(grep 'client-certificate-data' "$HOME"/.kube/config | awk '{print $2}' | base64 -d)
+}
+
+args=$(getopt -l "no-header:" -o "s:h" -- "$@")
+# eval set to set the positional arguments back to $args
+eval set -- "$args"
+
+while [[ $# -gt 0 ]]
+do
+   case $1 in
+   "config")
+    print_cert_kubeconfig
+    exit
+    ;;
+  "secret")
+    print_cert_secret "${args[@]}"
+    exit
+    ;;
+  *)
+    usage
+    echo::err "command $1 not found"
+    exit 1
+   esac
+done
 
 
-# base 64 encoded, X.509v3 certificate
-TEMP_DIR=$(mktemp --directory)
-TEMP_PEM=$TEMP_DIR/temp.pem
-grep 'client-certificate-data' "$HOME"/.kube/config | awk '{print $2}' | base64 -d > "$TEMP_PEM"
-# openssl storeutl permits to read a bundle does not take stdin as input
-crypto::certificate_to_text "$TEMP_PEM"
-rm -rf "$TEMP_DIR"
+
+
+
 
diff --git a/bin/kube-k3s b/bin/kube-k3s
--- a/bin/kube-k3s
+++ b/bin/kube-k3s
@@ -9,17 +9,27 @@ set -Eeuo pipefail
 source bashlib-error.sh
 error::set_trap
 
+# Where all PKI material are stored
+TLS_HOME=/var/lib/rancher/k3s/server/tls
+
 usage(){
+
   echo "Usage:"
   echo ""
   echo ""
   echo '```bash'
   # shellcheck disable=SC2005
-  echo "$(basename "$0") command"
+  echo "$(basename "$0") command args"
   echo '```'
   echo "where: command may be:"
   # shellcheck disable=SC2016
-  echo '  * `cert` : Print the certificates and their expiration date'
+  echo '  * `certs_expiration` : Print the certificates and their expiration date'
+  # shellcheck disable=SC2016
+  echo '  * `cert_print` : Print a single pem file'
+  # shellcheck disable=SC2016
+  echo '  * `cert_secret_print` : Print a kubernetes TLS cert secret'
+  echo ""
+  echo "All certs should be relative name (This script adds the directory: $TLS_HOME)"
 
 }
 
@@ -30,22 +40,32 @@ if [[ $HELP =~ -h|help ]]; then
   exit
 fi
 
-# Where all PKI material are stored
-TLS_HOME=/var/lib/rancher/k3s/server
 
-# Print the expiration
-function cert_expiration(){
-    find $TLS_HOME/tls -name '*.crt' | while read -r CERT_FILE; do
-      NOT_AFTER="$(openssl x509 -text -in "$CERT_FILE" | grep Not\ After)"
-      printf "%s\n%s\n\n" "$(basename "$CERT_FILE")" "$NOT_AFTER";
-    done
-}
 
-# Print the certs (bundle included)
-function cert_print(){
-    CRT_FILE_URI=$1
-    openssl storeutl -noout -text -certs "$CRT_FILE_URI"
-}
+args=$(getopt -l "no-header:" -o "s:h" -- "$@")
+# eval set to set the positional arguments back to $args
+eval set -- "$args"
 
-cert_expiration
+while [[ $# -gt 0 ]]
+do
+   case $1 in
+   "certs_expiration")
+    crypto::certs_expiration $TLS_HOME
+    exit
+    ;;
+  "cert_print")
+    crypto::cert_print $TLS_HOME/"$2"
+    exit
+    ;;
+  "cert_secret_print")
+    openssl storeutl -noout -text <(kubectl get secret -n kube-system k3s-serving -o jsonpath='{.data.tls\.crt}' | base64 -d)
+
+    exit
+    ;;
+  *)
+    usage
+    echo::err "command $1 not found"
+    exit 1
+   esac
+done
 
