First Alerting config

diff --git a/bin/kubectl-xenv b/bin/kubectl-xenv
--- a/bin/kubectl-xenv
+++ b/bin/kubectl-xenv
@@ -106,32 +106,33 @@ if [ "$KUBE_X_APP_NAME" != "" ]; then
   done
 
   if [ "$KUBE_X_APP_DIR" == "" ]; then
-    echo::err "No sub-directory with the name $KUBE_X_APP_NAME was found under the KUBE_X_APP_HOME paths ($KUBE_X_APP_HOME)"
-    exit 1
-  fi
-
-  # App specific env
-  # Should be first
-  # Go to the app dir and pop at err and exit
-  pushd "$KUBE_X_APP_DIR" >/dev/null || return 1
-  bash::trap 'popd >/dev/null' EXIT # EXIT execute also on error
-
-  # Load the env
-  if command::exists "direnv"; then
-      # Direnv should be explicitly called in non-interactive mode
-      # https://github.com/direnv/direnv/issues/262
-      if ! bash::is_interactive; then
-        eval "$(direnv export bash)"
-      fi
+    # App Name may be a component (example: alert manager)
+    echo::warn "No sub-directory with the name $KUBE_X_APP_NAME was found under the KUBE_X_APP_HOME paths ($KUBE_X_APP_HOME)"
   else
-    echo::warn "Direnv not found on path"
-    ENVRC_FILE="$KUBE_X_APP_DIR/.envrc"
-    if [ -f "$ENVRC_FILE" ]; then
-      # shellcheck disable=SC1090
-      source "$ENVRC_FILE"
+    # App specific env
+    # Should be first
+    # Go to the app dir and pop at err and exit
+    pushd "$KUBE_X_APP_DIR" >/dev/null || return 1
+    bash::trap 'popd >/dev/null' EXIT # EXIT execute also on error
+
+    # Load the env
+    if command::exists "direnv"; then
+        # Direnv should be explicitly called in non-interactive mode
+        # https://github.com/direnv/direnv/issues/262
+        if ! bash::is_interactive; then
+          eval "$(direnv export bash)"
+        fi
     else
-      echo::warn "File $ENVRC_FILE not found"
+      echo::warn "Direnv not found on path"
+      ENVRC_FILE="$KUBE_X_APP_DIR/.envrc"
+      if [ -f "$ENVRC_FILE" ]; then
+        # shellcheck disable=SC1090
+        source "$ENVRC_FILE"
+      else
+        echo::warn "File $ENVRC_FILE not found"
+      fi
     fi
+
   fi
 
 fi
