Values is now rendered in a kube function

diff --git a/bin/kube-x-cluster-app b/bin/kube-x-cluster-app
--- a/bin/kube-x-cluster-app
+++ b/bin/kube-x-cluster-app
@@ -10,33 +10,12 @@ source "${BASHLIB_LIBRARY_PATH:-}${BASHLIB_LIBRARY_PATH:+/}bashlib-echo.sh"
 source "${BASHLIB_LIBRARY_PATH:-}${BASHLIB_LIBRARY_PATH:+/}bashlib-doc.sh"
 # shellcheck source=../../bash-lib/lib/bashlib-template.sh
 source "${BASHLIB_LIBRARY_PATH:-}${BASHLIB_LIBRARY_PATH:+/}bashlib-template.sh"
+# shellcheck source=../../bash-lib/lib/bashlib-bash.sh
+source "${BASHLIB_LIBRARY_PATH:-}${BASHLIB_LIBRARY_PATH:+/}bashlib-bash.sh"
 # shellcheck source=./kube-x-lib.sh
 source "kube-x-lib.sh"
 
 
-generate_and_get_values_path(){
-
-  # Template
-  local KUBE_X_HELM_VALUES;
-  KUBE_X_HELM_VALUES=$(realpath "${KUBE_X_CLUSTER_DIR}/values.yaml")
-  if [ ! -f "$KUBE_X_HELM_VALUES" ]; then
-    echo::err "No helm file found at $KUBE_X_HELM_VALUES"
-    return 1;
-  fi
-
-  # Check the variables
-  if ! UNDEFINED_VARS=$(template::check_vars -f "$KUBE_X_HELM_VALUES"); then
-     # Should exit because of the strict mode
-     # but it was not working
-     echo::err "Values variables missing: ${UNDEFINED_VARS[*]} in file $KUBE_X_HELM_VALUES"
-     return 1
-  fi
-  local SHM_HELM_VALUES="/dev/shm/kube-x-helm-values.yml"
-
-  envsubst < "$KUBE_X_HELM_VALUES" >| "$SHM_HELM_VALUES"
-  echo "$SHM_HELM_VALUES"
-
-}
 
 apply(){
 
@@ -117,11 +96,10 @@ apply(){
     )
 
   # The kube-x values
-  if ! KUBE_X_VALUES_PATH=$(generate_and_get_values_path); then
-    echo::err "Error while trying to get the kube-x-helm values"
-    return 1
-  fi
-  HELM_INSTALL_COMMAND+=("-f" "${KUBE_X_VALUES_PATH}")
+  FINAL_VALUES_PATH="/dev/shm/kube-x-values.yml"
+  kube_x::print_values >| $FINAL_VALUES_PATH
+  bash::trap "rm $FINAL_VALUES_PATH" EXIT # EXIT execute also on error
+  HELM_INSTALL_COMMAND+=("-f" "${FINAL_VALUES_PATH}")
 
   if [ "${KUBE_X_HELM_INSTALL_OPTIONS:-}" != "" ]; then
     HELM_INSTALL_COMMAND+=("${KUBE_X_HELM_INSTALL_OPTIONS[@]}")
@@ -244,7 +222,9 @@ case "$COMMAND" in
     synopsis
     ;;
   "values")
-    yq "$(generate_and_get_values_path)"
+    kube_x::print_values
+#    VALUES=$(kube_x::print_values)
+#    cat "$VALUES" | yq
     ;;
   *)
     doc::help synopsis
diff --git a/bin/kube-x-helm-post-renderer b/bin/kube-x-helm-post-renderer
--- a/bin/kube-x-helm-post-renderer
+++ b/bin/kube-x-helm-post-renderer
@@ -12,7 +12,8 @@ source "${BASHLIB_LIBRARY_PATH:-}${BASHLIB_LIBRARY_PATH:+/}bashlib-doc.sh"
 source "${BASHLIB_LIBRARY_PATH:-}${BASHLIB_LIBRARY_PATH:+/}bashlib-bash.sh"
 # shellcheck source=../../bash-lib/lib/bashlib-command.sh
 source "${BASHLIB_LIBRARY_PATH:-}${BASHLIB_LIBRARY_PATH:+/}bashlib-command.sh"
-
+# shellcheck source=kube-x-lib.sh
+source kube-x-lib.sh
 
 APP_DIRECTORY="${1:-}"
 
@@ -35,7 +36,7 @@ if [ ! -d "$APP_DIRECTORY" ]; then
 fi
 
 # Values files
-CLUSTER_DIRECTORY=$PWD
+KUBE_X_CLUSTER_DIR=$PWD
 
 # The whole script run in the app directory
 pushd "$APP_DIRECTORY" > /dev/null
@@ -58,26 +59,9 @@ if [ -d "$JSONNET_DIR" ]; then
     jb update
   fi
 
-  # Determine the values
-  CLUSTER_VALUES_PATH="$CLUSTER_DIRECTORY/values.yaml"
-  if [ ! -f "$CLUSTER_VALUES_PATH" ]; then
-    echo::err "The values file ($CLUSTER_VALUES_PATH) does not exist"
-    exit 1
-  fi
-  SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
-  DEFAULT_VALUES_PATH=$(realpath "$SCRIPT_DIR/../resources/apps/kube-x/values.yaml")
-  if [ ! -f "$DEFAULT_VALUES_PATH" ]; then
-    echo::err "Internal Error: The default values file ($DEFAULT_VALUES_PATH) was not found"
-    exit 1
-  fi
-
-  # Before merge, values should be below the kube_x property
-  DEFAULT_VALUES_PATH_KUBE_X_PROPERTY="/dev/shm/kube-x-helm-post-renderer-default-values.yml"
-  yq e ".kube_x = load(\"$DEFAULT_VALUES_PATH\")" >| $DEFAULT_VALUES_PATH_KUBE_X_PROPERTY
-
   FINAL_VALUES_PATH="/dev/shm/kube-x-helm-post-renderer-values.yml"
-  # shellcheck disable=SC2016
-  yq eval-all '. as $item ireduce ({}; . * $item )' "$DEFAULT_VALUES_PATH_KUBE_X_PROPERTY" "$CLUSTER_VALUES_PATH" >| "$FINAL_VALUES_PATH"
+  kube_x::print_values >| $FINAL_VALUES_PATH
+  bash::trap "rm $FINAL_VALUES_PATH" EXIT # EXIT executes also on error
 
   for JSONNET_FILE in jsonnet/*.jsonnet; do
 
