Grafana Dashboard on the road

diff --git a/bin/kube-x-cluster-app b/bin/kube-x-cluster-app
--- a/bin/kube-x-cluster-app
+++ b/bin/kube-x-cluster-app
@@ -14,7 +14,7 @@ source "${BASHLIB_LIBRARY_PATH:-}${BASHLIB_LIBRARY_PATH:+/}bashlib-template.sh"
 source "kube-x-lib.sh"
 
 
-generate_and_get_helm_values_path(){
+generate_and_get_values_path(){
 
   # Default
   # export is mandatory to go in a subshell
@@ -31,7 +31,8 @@ generate_and_get_helm_values_path(){
   fi
 
   # Template
-  local KUBE_X_HELM_VALUES="${KUBE_X_CLUSTER_DIR}/helm-values.yaml"
+  local KUBE_X_HELM_VALUES;
+  KUBE_X_HELM_VALUES=$(realpath "${KUBE_X_CLUSTER_DIR}/values.yaml")
   if [ ! -f "$KUBE_X_HELM_VALUES" ]; then
     echo::err "No helm file found at $KUBE_X_HELM_VALUES"
     return 1;
@@ -41,7 +42,7 @@ generate_and_get_helm_values_path(){
   if ! UNDEFINED_VARS=$(template::check_vars -f "$KUBE_X_HELM_VALUES"); then
      # Should exit because of the strict mode
      # but it was not working
-     echo::err "Helm Values variables missing: ${UNDEFINED_VARS[*]}"
+     echo::err "Values variables missing: ${UNDEFINED_VARS[*]} in file $KUBE_X_HELM_VALUES"
      return 1
   fi
   local SHM_HELM_VALUES="/dev/shm/kube-x-helm-values.yml"
@@ -77,10 +78,11 @@ apply(){
   if [ -f "$KUBE_X_ENV_FILE" ]; then
      echo::debug "Sourcing env file $KUBE_X_ENV_FILE"
      # shellcheck disable=SC1090
-     source "$KUBE_X_ENV_FILE"
+     if ! source "$KUBE_X_ENV_FILE"; then
+       echo::err "Error while importing the envrc file $KUBE_X_ENV_FILE"
+       return 1
+     fi
   fi
-
-
 
   read -r APP_NAMESPACE APP_NAME <<< "$(kube::get_qualified_app_name "$APP_NAME")"
   echo "$APP_NAMESPACE $APP_NAME"
@@ -146,7 +148,7 @@ apply(){
     )
 
   # The kube-x values
-  if ! KUBE_X_VALUES_PATH=$(generate_and_get_helm_values_path); then
+  if ! KUBE_X_VALUES_PATH=$(generate_and_get_values_path); then
     echo::err "Error while trying to get the kube-x-helm values"
     return 1
   fi
@@ -253,7 +255,7 @@ case "$COMMAND" in
     synopsis
     ;;
   "values")
-    cat "$(generate_and_get_helm_values_path)"
+    cat "$(generate_and_get_values_path)"
     ;;
   *)
     doc::help synopsis
