Traefik !

diff --git a/bin/kubee-cluster b/bin/kubee-cluster
--- a/bin/kubee-cluster
+++ b/bin/kubee-cluster
@@ -1,23 +1,9 @@
 #!/usr/bin/env bash
 
-# shellcheck source=../..//bash-lib/lib/bashlib-error.sh
-source "${BASHLIB_LIBRARY_PATH:-}${BASHLIB_LIBRARY_PATH:+/}bashlib-error.sh"
-error::set_strict_mode
-error::set_trap
-# shellcheck source=../../bash-lib/lib/bashlib-echo.sh
-source "${BASHLIB_LIBRARY_PATH:-}${BASHLIB_LIBRARY_PATH:+/}bashlib-echo.sh"
-# shellcheck source=../../bash-lib/lib/bashlib-bash.sh
-source "${BASHLIB_LIBRARY_PATH:-}${BASHLIB_LIBRARY_PATH:+/}bashlib-bash.sh"
-# shellcheck source=../../bash-lib/lib/bashlib-doc.sh
-source "${BASHLIB_LIBRARY_PATH:-}${BASHLIB_LIBRARY_PATH:+/}bashlib-doc.sh"
-# shellcheck source=../../bash-lib/lib/bashlib-command.sh
-source "${BASHLIB_LIBRARY_PATH:-}${BASHLIB_LIBRARY_PATH:+/}bashlib-command.sh"
+
 # shellcheck source=../../bash-lib/lib/bashlib-template.sh
 source "${BASHLIB_LIBRARY_PATH:-}${BASHLIB_LIBRARY_PATH:+/}bashlib-template.sh"
-# shellcheck source=../../bash-lib/lib/bashlib-script.sh
-source "${BASHLIB_LIBRARY_PATH:-}${BASHLIB_LIBRARY_PATH:+/}bashlib-script.sh"
-# shellcheck source=./kubee-lib.sh
-source "kubee-lib.sh"
+
 
 
 inventory_file(){
@@ -38,6 +24,10 @@ inventory_file(){
      # k3s version
      # https://github.com/k3s-io/k3s/releases
      export KUBEE_CLUSTER_K3S_VERSION=${KUBEE_CLUSTER_K3S_VERSION:-"v1.32.0+k3s1"}
+
+     # Empty by default
+     export KUBEE_CLUSTER_SERVER_ADMIN_USERNAME=${KUBEE_CLUSTER_SERVER_ADMIN_USERNAME:-""}
+     export KUBEE_CLUSTER_SERVER_ADMIN_PUBLIC_KEY=${KUBEE_CLUSTER_SERVER_ADMIN_PUBLIC_KEY:-""}
 
      # Connection type to the host. This can be the name of any Ansible connection plugin.
      # The default is ssh
@@ -152,8 +142,8 @@ EOT
 
 
 # Assign the first argument to a string
-COMMAND="${1:-}"
-if [ "$COMMAND" = "" ]; then
+CLUSTER_COMMAND="${1:-}"
+if [ "$CLUSTER_COMMAND" = "" ]; then
     synopsis
     echo::err "A command is mandatory"
     exit 1
@@ -162,12 +152,12 @@ shift  # Remove the first argument from the argument list
 
 # Help Asked should not fail for the doc
 # We test if before the error warning
-if [[ $COMMAND =~ help|-h|--help ]]; then
+if [[ $CLUSTER_COMMAND =~ help|-h|--help ]]; then
   doc::help synopsis
   exit
 fi
 
-if [[ $COMMAND == "synopsis" ]]; then
+if [[ $CLUSTER_COMMAND == "synopsis" ]]; then
   synopsis
   exit
 fi
@@ -199,18 +189,28 @@ fi
 bash::trap "rm $SHM_INVENTORY_FILE" EXIT
 
 # Key file
-if [ "$KUBEE_CLUSTER_PRIVATE_KEY" != "" ]; then
-  export ANSIBLE_PRIVATE_KEY_FILE=/dev/shm/ssh-key
-  echo "$KUBEE_CLUSTER_PRIVATE_KEY" >| "$ANSIBLE_PRIVATE_KEY_FILE"
-  bash::trap "rm $ANSIBLE_PRIVATE_KEY_FILE" EXIT
+if [ "${KUBEE_CLUSTER_SERVER_CONNECTION_PRIVATE_KEY_FILE:-""}" != "" ]; then
+  export ANSIBLE_PRIVATE_KEY_FILE="${KUBEE_CLUSTER_SERVER_CONNECTION_PRIVATE_KEY_FILE}"
+else
+  if [ "${KUBEE_CLUSTER_SERVER_CONNECTION_PRIVATE_KEY:-""}" != "" ]; then
+    export ANSIBLE_PRIVATE_KEY_FILE="/dev/shm/ssh-key"
+    echo "$KUBEE_CLUSTER_SERVER_CONNECTION_PRIVATE_KEY" >| "$ANSIBLE_PRIVATE_KEY_FILE"
+    bash::trap "rm $ANSIBLE_PRIVATE_KEY_FILE" EXIT
+  else
+    echo::warn "No server connection private key defined."
+    echo::warn "The env KUBEE_CLUSTER_SERVER_CONNECTION_PRIVATE_KEY_FILE and KUBEE_CLUSTER_SERVER_CONNECTION_PRIVATE_KEY were empty"
+    echo::warn "Ssh will try to connect with the default key file in ~/.ssh"
+    echo::warn "If there is none, the connection will failed"
+  fi
+fi
+if [ "${ANSIBLE_PRIVATE_KEY_FILE:-""}" != "" ]; then
   # to avoid Permissions 0644 for '/tmp/ssh-key' are too open
   # as we mount with the current user, docker inherit the permissions
   chmod 600 "$ANSIBLE_PRIVATE_KEY_FILE"
 fi
 
 
-
-case $COMMAND in
+case $CLUSTER_COMMAND in
 "play")
     play "$@" || error::exit $?
     ;;
@@ -225,6 +225,6 @@ case $COMMAND in
     ;;
 *)
   doc::help synopsis
-  echo::err "Command $COMMAND is unknown"
+  echo::err "Command $CLUSTER_COMMAND is unknown"
   exit 1
 esac
diff --git a/bin/kubee-helmet b/bin/kubee-helmet
--- a/bin/kubee-helmet
+++ b/bin/kubee-helmet
@@ -159,7 +159,7 @@ install_crd_first(){
   # recursion
   # We don't use helm directly as we have now CRD charts that are only with Jsonnet
   echo::info "Installing CRD Chart $PACKAGE_CRDS_NAME in namespace $CHART_NAMESPACE"
-  if ! echo::eval "$(basename "$0") play -n $CHART_NAMESPACE $PACKAGE_CRDS_NAME"; then
+  if ! echo::eval "kubee -n $CHART_NAMESPACE helmet play $PACKAGE_CRDS_NAME"; then
     return 1
   fi
 
@@ -268,9 +268,16 @@ apply(){
   # example: "--set-file kubee.traefik.defaultCertificate.cert=cert/kubee.dev+1.pem"
   echo::eval "pushd $KUBEE_CLUSTER_DIR 1>$COMMAND_STDOUT_FD"
   bash::trap "popd 1>$COMMAND_STDOUT_FD" EXIT
-  # Silence or not output
-  # ie for template: wrote out/xxx/templates/xxx.yml
-  HELM_COMMAND+=("2>$COMMAND_STDOUT_FD" "1>$COMMAND_STDOUT_FD")
+
+  # Silence for template command
+  # wrote out/xxx/templates/xxx.yml
+  if [ "$COMMAND" == "template" ]; then
+    HELM_COMMAND+=("1>$COMMAND_STDOUT_FD")
+  fi
+
+  # Silence or no output
+  HELM_COMMAND+=("2>$COMMAND_STDOUT_FD")
+
   echo::info "Executing Helm $COMMAND"
   if ! echo::eval "${HELM_COMMAND[*]}"; then
     echo::err "An error occurs during the command $COMMAND"
@@ -382,51 +389,55 @@ print_values(){
   #
   local CHART_VALUES_FILES=()
 
-  # Loop over the dependencies
-  while IFS=, read -r DEPENDENCY_CHART_NAME DEPENDENCY_CHART_ALIAS DEPENDENCY_CHART_REPOSITORY DEPENDENCY_CHART_VERSION; do
+  local DEPENDENCIES;
+  DEPENDENCIES="$(yq -r '.dependencies[] | [ .name + "," + .alias + "," + .repository + "," + .version] | join("\n")' "$ACTUAL_CHART_FILE")"
+  if [ "$DEPENDENCIES" != "" ]; then
+    # Loop over the dependencies
+    while IFS=, read -r DEPENDENCY_CHART_NAME DEPENDENCY_CHART_ALIAS DEPENDENCY_CHART_REPOSITORY DEPENDENCY_CHART_VERSION; do
 
-            if [ "$DEPENDENCY_CHART_ALIAS" == "" ] || [ "$DEPENDENCY_CHART_ALIAS" == "null" ]; then
-              echo::err "All dependency should have an alias"
-              echo::err "The repository $DEPENDENCY_CHART_REPOSITORY does not have one"
-              return 1
-            fi
-            local HELM_SHOW_VALUE_COMMAND=(
-              'helm' 'show' 'values'
-            )
-            case "$DEPENDENCY_CHART_REPOSITORY" in
-              file://.*)
-                # Local
-                # The name of the chart is the path to the chart directory
-                # Delete the file scheme (not supported by `helm get values`)
-                DEPENDENCY_CHART="$CHART_DIRECTORY/${DEPENDENCY_CHART_REPOSITORY#"file://"}"
-                HELM_SHOW_VALUE_COMMAND+=("$DEPENDENCY_CHART")
-              ;;
-              *)
-                # Other scheme: Http, Oci scheme, ...
-                HELM_SHOW_VALUE_COMMAND+=("--repo" "$DEPENDENCY_CHART_REPOSITORY")
-                HELM_SHOW_VALUE_COMMAND+=("--version" "$DEPENDENCY_CHART_VERSION")
-                HELM_SHOW_VALUE_COMMAND+=("$DEPENDENCY_CHART_NAME")
-              ;;
-            esac
-            local SHM_DEPENDENCY_CHART_VALUES_FILE="$CHART_OUTPUT_VALUES_DIR/${DEPENDENCY_CHART_ALIAS}_default_non_scoped.yml"
-            HELM_SHOW_VALUE_COMMAND+=(">| $SHM_DEPENDENCY_CHART_VALUES_FILE")
-            # 2>COMMAND_STDOUT_FD to silence: walk.go:75: found symbolic link in path
-            HELM_SHOW_VALUE_COMMAND+=("2>$COMMAND_STDOUT_FD")
-            if ! echo::eval "${HELM_SHOW_VALUE_COMMAND[*]}"; then
-              echo::err "Error while trying to the get values for the Chart $DEPENDENCY_CHART_ALIAS"
-              return 1
-            fi
-            # The default value should be under the alias key (ie scoped)
-            local SHM_DEPENDENCY_CHART_VALUES_FILE_WITH_SCOPE="$CHART_OUTPUT_VALUES_DIR/${DEPENDENCY_CHART_ALIAS}_default.yml"
-            # --null-input flag: does not have any input as we create a new file
-            if ! echo::eval "yq eval --null-input '.$DEPENDENCY_CHART_ALIAS = (load(\"$SHM_DEPENDENCY_CHART_VALUES_FILE\"))' >| $SHM_DEPENDENCY_CHART_VALUES_FILE_WITH_SCOPE"; then
-              echo::err "Error while processing the chart values file $SHM_DEPENDENCY_CHART_VALUES_FILE"
-              return 1
-            fi
-            rm "$SHM_DEPENDENCY_CHART_VALUES_FILE"
-            CHART_VALUES_FILES+=("$SHM_DEPENDENCY_CHART_VALUES_FILE_WITH_SCOPE")
-            echo::debug "Values file generated: ${SHM_DEPENDENCY_CHART_VALUES_FILE_WITH_SCOPE}"
-  done <<< "$(yq -r '.dependencies[] | [ .name + "," + .alias + "," + .repository + "," + .version] | join("\n")' "$ACTUAL_CHART_FILE")"
+              if [ "$DEPENDENCY_CHART_ALIAS" == "" ] || [ "$DEPENDENCY_CHART_ALIAS" == "null" ]; then
+                echo::err "All dependency should have an alias"
+                echo::err "The repository $DEPENDENCY_CHART_REPOSITORY does not have one"
+                return 1
+              fi
+              local HELM_SHOW_VALUE_COMMAND=(
+                'helm' 'show' 'values'
+              )
+              case "$DEPENDENCY_CHART_REPOSITORY" in
+                file://.*)
+                  # Local
+                  # The name of the chart is the path to the chart directory
+                  # Delete the file scheme (not supported by `helm get values`)
+                  DEPENDENCY_CHART="$CHART_DIRECTORY/${DEPENDENCY_CHART_REPOSITORY#"file://"}"
+                  HELM_SHOW_VALUE_COMMAND+=("$DEPENDENCY_CHART")
+                ;;
+                *)
+                  # Other scheme: Http, Oci scheme, ...
+                  HELM_SHOW_VALUE_COMMAND+=("--repo" "$DEPENDENCY_CHART_REPOSITORY")
+                  HELM_SHOW_VALUE_COMMAND+=("--version" "$DEPENDENCY_CHART_VERSION")
+                  HELM_SHOW_VALUE_COMMAND+=("$DEPENDENCY_CHART_NAME")
+                ;;
+              esac
+              local SHM_DEPENDENCY_CHART_VALUES_FILE="$CHART_OUTPUT_VALUES_DIR/${DEPENDENCY_CHART_ALIAS}_default_non_scoped.yml"
+              HELM_SHOW_VALUE_COMMAND+=(">| $SHM_DEPENDENCY_CHART_VALUES_FILE")
+              # 2>COMMAND_STDOUT_FD to silence: walk.go:75: found symbolic link in path
+              HELM_SHOW_VALUE_COMMAND+=("2>$COMMAND_STDOUT_FD")
+              if ! echo::eval "${HELM_SHOW_VALUE_COMMAND[*]}"; then
+                echo::err "Error while trying to the get values for the Chart $DEPENDENCY_CHART_ALIAS"
+                return 1
+              fi
+              # The default value should be under the alias key (ie scoped)
+              local SHM_DEPENDENCY_CHART_VALUES_FILE_WITH_SCOPE="$CHART_OUTPUT_VALUES_DIR/${DEPENDENCY_CHART_ALIAS}_default.yml"
+              # --null-input flag: does not have any input as we create a new file
+              if ! echo::eval "yq eval --null-input '.$DEPENDENCY_CHART_ALIAS = (load(\"$SHM_DEPENDENCY_CHART_VALUES_FILE\"))' >| $SHM_DEPENDENCY_CHART_VALUES_FILE_WITH_SCOPE"; then
+                echo::err "Error while processing the chart values file $SHM_DEPENDENCY_CHART_VALUES_FILE"
+                return 1
+              fi
+              rm "$SHM_DEPENDENCY_CHART_VALUES_FILE"
+              CHART_VALUES_FILES+=("$SHM_DEPENDENCY_CHART_VALUES_FILE_WITH_SCOPE")
+              echo::debug "Values file generated: ${SHM_DEPENDENCY_CHART_VALUES_FILE_WITH_SCOPE}"
+    done <<< "$DEPENDENCIES"
+  fi
 
 
   # Chart Own values files
