Traefik on the road

diff --git a/bin/kubee b/bin/kubee
--- a/bin/kubee
+++ b/bin/kubee
@@ -51,7 +51,8 @@ fi
 export KUBEE_CONNECTION_NAMESPACE=${KUBEE_CONNECTION_NAMESPACE:-"default"}
 export KUBEE_CLUSTER_NAME=${KUBEE_CLUSTER_NAME:-}
 # Echo variables
-# The destination of any std for an executed command
+# COMMAND_STDOUT_FD is where the stdout, stderr of executed command should go,
+# exported because it's used also in the helm post-renderer
 # default to null and is set to stderr or tty for debug level
 export COMMAND_STDOUT_FD="/dev/null"
 # Default level
@@ -113,7 +114,7 @@ kubee::set_env
 
 # Advertise the --debug flag if any error
 # shellcheck disable=SC2016
-bash::trap 'exit_code=$?; if [ $exit_code -ne 0 ]; then echo -e "\033[0;33mScript failed use the --debug flag to get more information\033[0m"; fi' EXIT
+bash::trap 'exit_code=$?; if [ $exit_code -ne 0 ]; then echo -e "\033[0;33mScript failed use the global `kubee --debug` flag to get more information\033[0m"; fi' EXIT
 
 case "$KUBEE_COMMAND" in
   "cluster")
diff --git a/bin/kubee-helmet b/bin/kubee-helmet
--- a/bin/kubee-helmet
+++ b/bin/kubee-helmet
@@ -217,10 +217,11 @@ apply(){
   HELM_COMMAND+=("-f" "${CHART_VALUES_PATH}")
 
 
-  HELM_COMMAND+=(
-    "--namespace" "$CHART_NAMESPACE"
-    "--create-namespace"
-  )
+  HELM_COMMAND+=("--namespace" "$CHART_NAMESPACE")
+  if [[ "$COMMAND" =~ 'play'|'install' ]]; then
+    # Create namespace only on install
+    HELM_COMMAND+=("--create-namespace");
+  fi
 
   # Install CRD first
   if ! install_crd_first; then
@@ -232,7 +233,8 @@ apply(){
   # 2>COMMAND_STDOUT_FD to silence: walk.go:75: found symbolic link in path
   echo::info "Executing Helm Dependency Update"
   echo::eval "helm dependency update ${HELM_EXTRA_FLAGS[*]} $CHART_DIRECTORY 1>$COMMAND_STDOUT_FD 2>$COMMAND_STDOUT_FD"
-  HELM_COMMAND+=( "--dependency-update" )
+  # Note that helm has also a flag
+  # HELM_COMMAND+=( "--dependency-update" )
 
   # Options ???
   if [ "${KUBEE_HELM_INSTALL_OPTIONS:-}" != "" ]; then
@@ -266,6 +268,9 @@ apply(){
   # example: "--set-file kubee.traefik.defaultCertificate.cert=cert/kubee.dev+1.pem"
   echo::eval "pushd $KUBEE_CLUSTER_DIR 1>$COMMAND_STDOUT_FD"
   bash::trap "popd 1>$COMMAND_STDOUT_FD" EXIT
+  # Silence or not output
+  # ie for template: wrote out/xxx/templates/xxx.yml
+  HELM_COMMAND+=("2>$COMMAND_STDOUT_FD" "1>$COMMAND_STDOUT_FD")
   echo::info "Executing Helm $COMMAND"
   if ! echo::eval "${HELM_COMMAND[*]}"; then
     echo::err "An error occurs during the command $COMMAND"
@@ -377,42 +382,52 @@ print_values(){
   #
   local CHART_VALUES_FILES=()
 
-  local -A dependencies
-  eval "dependencies=($(yq -r '.dependencies[] | ["[" + .alias + "]=" + .repository] | join(" ")' "$ACTUAL_CHART_FILE"))"
-  for DEPENDENCY_CHART_ALIAS in "${!dependencies[@]}"; do
-      local DEPENDENCY_CHART_REPOSITORY=${dependencies[$DEPENDENCY_CHART_ALIAS]}
-      if [ "$DEPENDENCY_CHART_ALIAS" == "" ]; then
-        echo::err "All dependency should have an alias"
-        echo::err "The repository $DEPENDENCY_CHART_REPOSITORY does not have one"
-        return 1
-      fi
+  # Loop over the dependencies
+  while IFS=, read -r DEPENDENCY_CHART_NAME DEPENDENCY_CHART_ALIAS DEPENDENCY_CHART_REPOSITORY DEPENDENCY_CHART_VERSION; do
 
-      case "$DEPENDENCY_CHART_REPOSITORY" in
-        file://.*)
-          # Delete the file scheme (not supported by `helm get values`
-          DEPENDENCY_CHART_REPOSITORY="$CHART_DIRECTORY/${DEPENDENCY_CHART_REPOSITORY#"file://"}"
-        ;;
-        *)
-          # Other scheme
-        ;;
-      esac
-      local SHM_DEPENDENCY_CHART_VALUES_FILE="$CHART_OUTPUT_VALUES_DIR/${DEPENDENCY_CHART_ALIAS}_default_non_scoped.yml"
-      # 2>COMMAND_STDOUT_FD to silence: walk.go:75: found symbolic link in path
-      if ! echo::eval "helm show values $DEPENDENCY_CHART_REPOSITORY >| $SHM_DEPENDENCY_CHART_VALUES_FILE 2>$COMMAND_STDOUT_FD"; then
-        echo::err "Error while trying to the get values for the Chart $DEPENDENCY_CHART_ALIAS"
-        return 1
-      fi
-      # The default value should be under the alias key (ie scoped)
-      local SHM_DEPENDENCY_CHART_VALUES_FILE_WITH_SCOPE="$CHART_OUTPUT_VALUES_DIR/${DEPENDENCY_CHART_ALIAS}_default.yml"
-      # --null-input flag: does not have any input as we create a new file
-      if ! echo::eval "yq eval --null-input '.$DEPENDENCY_CHART_ALIAS = (load(\"$SHM_DEPENDENCY_CHART_VALUES_FILE\"))' >| $SHM_DEPENDENCY_CHART_VALUES_FILE_WITH_SCOPE"; then
-        echo::err "Error while processing the chart values file $SHM_DEPENDENCY_CHART_VALUES_FILE"
-        return 1
-      fi
-      rm "$SHM_DEPENDENCY_CHART_VALUES_FILE"
-      CHART_VALUES_FILES+=("$SHM_DEPENDENCY_CHART_VALUES_FILE_WITH_SCOPE")
-      echo::debug "Values file generated: ${SHM_DEPENDENCY_CHART_VALUES_FILE_WITH_SCOPE}"
-  done
+            if [ "$DEPENDENCY_CHART_ALIAS" == "" ] || [ "$DEPENDENCY_CHART_ALIAS" == "null" ]; then
+              echo::err "All dependency should have an alias"
+              echo::err "The repository $DEPENDENCY_CHART_REPOSITORY does not have one"
+              return 1
+            fi
+            local HELM_SHOW_VALUE_COMMAND=(
+              'helm' 'show' 'values'
+            )
+            case "$DEPENDENCY_CHART_REPOSITORY" in
+              file://.*)
+                # Local
+                # The name of the chart is the path to the chart directory
+                # Delete the file scheme (not supported by `helm get values`)
+                DEPENDENCY_CHART="$CHART_DIRECTORY/${DEPENDENCY_CHART_REPOSITORY#"file://"}"
+                HELM_SHOW_VALUE_COMMAND+=("$DEPENDENCY_CHART")
+              ;;
+              *)
+                # Other scheme: Http, Oci scheme, ...
+                HELM_SHOW_VALUE_COMMAND+=("--repo" "$DEPENDENCY_CHART_REPOSITORY")
+                HELM_SHOW_VALUE_COMMAND+=("--version" "$DEPENDENCY_CHART_VERSION")
+                HELM_SHOW_VALUE_COMMAND+=("$DEPENDENCY_CHART_NAME")
+              ;;
+            esac
+            local SHM_DEPENDENCY_CHART_VALUES_FILE="$CHART_OUTPUT_VALUES_DIR/${DEPENDENCY_CHART_ALIAS}_default_non_scoped.yml"
+            HELM_SHOW_VALUE_COMMAND+=(">| $SHM_DEPENDENCY_CHART_VALUES_FILE")
+            # 2>COMMAND_STDOUT_FD to silence: walk.go:75: found symbolic link in path
+            HELM_SHOW_VALUE_COMMAND+=("2>$COMMAND_STDOUT_FD")
+            if ! echo::eval "${HELM_SHOW_VALUE_COMMAND[*]}"; then
+              echo::err "Error while trying to the get values for the Chart $DEPENDENCY_CHART_ALIAS"
+              return 1
+            fi
+            # The default value should be under the alias key (ie scoped)
+            local SHM_DEPENDENCY_CHART_VALUES_FILE_WITH_SCOPE="$CHART_OUTPUT_VALUES_DIR/${DEPENDENCY_CHART_ALIAS}_default.yml"
+            # --null-input flag: does not have any input as we create a new file
+            if ! echo::eval "yq eval --null-input '.$DEPENDENCY_CHART_ALIAS = (load(\"$SHM_DEPENDENCY_CHART_VALUES_FILE\"))' >| $SHM_DEPENDENCY_CHART_VALUES_FILE_WITH_SCOPE"; then
+              echo::err "Error while processing the chart values file $SHM_DEPENDENCY_CHART_VALUES_FILE"
+              return 1
+            fi
+            rm "$SHM_DEPENDENCY_CHART_VALUES_FILE"
+            CHART_VALUES_FILES+=("$SHM_DEPENDENCY_CHART_VALUES_FILE_WITH_SCOPE")
+            echo::debug "Values file generated: ${SHM_DEPENDENCY_CHART_VALUES_FILE_WITH_SCOPE}"
+  done <<< "$(yq -r '.dependencies[] | [ .name + "," + .alias + "," + .repository + "," + .version] | join("\n")' "$ACTUAL_CHART_FILE")"
+
 
   # Chart Own values files
   local CHART_VALUES_FILE="$CHART_DIRECTORY/values.yaml"
@@ -460,21 +475,15 @@ print_values(){
 ##########################
 ## Collect the options
 ##########################
-args=$(getopt -l "cluster:,debug,skip-schema-validation,output-dir:,out" -o "c:o:" -- "$@")
+args=$(getopt -l "skip-schema-validation,output-dir:,out" -o "o:" -- "$@")
 # eval set to set the positional arguments back to $args
 eval set -- "$args"
 KUBEE_CLUSTER_NAME=${KUBEE_CLUSTER_NAME:-}
 HELM_EXTRA_FLAGS=()
 OPTION_OUTPUT_DIR=""
-export COMMAND_STDOUT_FD="/dev/null" # where the stdout, stderr of command should go, exported because it's used also in the helm post-renderer
 while [[ $# -gt 0 ]]
 do
    case "$1" in
-      "--cluster"|"-c")
-        shift
-        KUBEE_CLUSTER_NAME=${1}
-        shift
-      ;;
       "--output-dir"|"-o")
         shift
         OPTION_OUTPUT_DIR=${1}
